#include <cassert>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#ifdef USE_MPI
#include "cfmpi.hpp"
#endif

#include "finiteElement.hpp"
#include "baseProblem.hpp"
#include "paraview.hpp"
#include "../num/matlab.hpp"

// -----------------------------------------------------------------------------
// Classical fitted-FEM Maxwell cavity eigenvalue comparison.
//
// Meshes are generated by generate_fitted_maxwell_meshes.py.  The preferred
// names follow the library's existing extensionless Medit convention:
//
//   cube_0, cube_1, cube_2
//   spherical_shell_0, spherical_shell_1, spherical_shell_2
//
// For compatibility, files ending in .mesh are accepted as well.
//
// Methods:
//   wave      : Ned0 curl-curl eigenproblem
//   kikuchi   : Ned0-P1 mixed eigenproblem
//   3field    : Ned0-RT0-P0 first-order eigenproblem
//
// This file contains no cut geometry, ghost penalties, patch stabilization, or
// pressure regularization.  Integration is over the fitted tetrahedral Mesh3
// directly.
//
// Boundary conditions:
//   wave    : n x u = 0 by symmetric fitted H(curl)-Nitsche terms.
//   kikuchi : n x u = 0 by the same H(curl)-Nitsche terms, and p = 0 by the
//              symmetric mixed boundary terms
//                  -(u.n,q)_boundary -(p,v.n)_boundary
//              together with the penalty lambda_p h^{-1}(p,q)_boundary.
//   3field  : n x u = 0 is natural in the fitted mixed formulation, so no
//              essential boundary degrees of freedom are eliminated.
// -----------------------------------------------------------------------------

using namespace globalVariable;

enum class ExampleKind { Cube, SphericalShell };

static std::string example_name(ExampleKind ex) {
    return (ex == ExampleKind::Cube) ? "cube" : "spherical_shell";
}

namespace FittedEigenData {
    R eps = 1.;
    R mu  = 1.;

    R shell_center[3] = {0.5 * M_PI, 0.5 * M_PI, 0.5 * M_PI};
    R radius_inner = M_PI / 5.;
    R radius_outer = M_PI / 3.;

    // Radial harmonic representative on the shell, in centred coordinates.
    // It is smooth because r >= radius_inner > 0.
    R fun_harmonic_two_form(double *P, int i) {
        const R x = P[0] - shell_center[0];
        const R y = P[1] - shell_center[1];
        const R z = P[2] - shell_center[2];
        const R r2 = x*x + y*y + z*z;
        const R r  = std::sqrt(r2);
        const R r3 = r2 * r;
        if (i == 0) return x / r3;
        if (i == 1) return y / r3;
        return z / r3;
    }
}

struct Config {
    int nx0 = 7;
    int levels = 3;

    bool do_wave = true;
    bool do_kikuchi = true;
    bool do_3field = true;

    std::vector<ExampleKind> examples = {
        ExampleKind::Cube,
        ExampleKind::SphericalShell
    };

    std::string mesh_dir = "../cpp/mainFiles/meshes";
    std::string prefix = "eigcmp_fitted_nitsche";

    R nitsche_penalty = 1e2;
    R pressure_penalty = 1e2;

    bool filter_harmonic_in_shell = true;
};

static bool use_harmonic_filter(const Config &cfg, ExampleKind ex) {
    return cfg.filter_harmonic_in_shell && ex == ExampleKind::SphericalShell;
}

static void print_usage(const char *exe) {
    std::cout
        << "Usage: " << exe << " [options]\n\n"
        << "Options:\n"
        << "  --mesh-dir DIR          directory containing the generated .msh files\n"
        << "  --levels N              number of mesh levels, default 3\n"
        << "  --nx0 N                 value defining h0=pi/(nx0-1), default 7\n"
        << "  --prefix NAME           output prefix, default eigcmp_fitted_nitsche\n"
        << "  --nitsche-penalty X     penalty for n x u = 0, default 1e2\n"
        << "  --pressure-penalty X    penalty for p = 0, default 1e2\n"
        << "  --method all|wave|kikuchi|3field\n"
        << "  --example all|cube|spherical_shell\n"
        << "  --no-harmonic-filter    do not constrain the shell harmonic field\n"
        << "  --help\n";
}

static void parse_args(int argc, char **argv, Config &cfg) {
    for (int a = 1; a < argc; ++a) {
        const std::string key(argv[a]);
        auto require_value = [&](const std::string &name) -> std::string {
            if (a + 1 >= argc) {
                std::cerr << "Missing value after " << name << std::endl;
                std::exit(2);
            }
            return std::string(argv[++a]);
        };

        if (key == "--help" || key == "-h") {
            print_usage(argv[0]);
            std::exit(0);
        } else if (key == "--mesh-dir") {
            cfg.mesh_dir = require_value(key);
        } else if (key == "--levels") {
            cfg.levels = std::stoi(require_value(key));
        } else if (key == "--nx0") {
            cfg.nx0 = std::stoi(require_value(key));
        } else if (key == "--prefix") {
            cfg.prefix = require_value(key);
        } else if (key == "--nitsche-penalty") {
            cfg.nitsche_penalty = std::stod(require_value(key));
        } else if (key == "--pressure-penalty") {
            cfg.pressure_penalty = std::stod(require_value(key));
        } else if (key == "--no-harmonic-filter") {
            cfg.filter_harmonic_in_shell = false;
        } else if (key == "--method") {
            const std::string method = require_value(key);
            cfg.do_wave = cfg.do_kikuchi = cfg.do_3field = false;
            if (method == "all") {
                cfg.do_wave = cfg.do_kikuchi = cfg.do_3field = true;
            } else if (method == "wave") {
                cfg.do_wave = true;
            } else if (method == "kikuchi") {
                cfg.do_kikuchi = true;
            } else if (method == "3field" || method == "threefield") {
                cfg.do_3field = true;
            } else {
                std::cerr << "Unknown method: " << method << std::endl;
                std::exit(2);
            }
        } else if (key == "--example") {
            const std::string ex = require_value(key);
            cfg.examples.clear();
            if (ex == "all") {
                cfg.examples.push_back(ExampleKind::Cube);
                cfg.examples.push_back(ExampleKind::SphericalShell);
            } else if (ex == "cube") {
                cfg.examples.push_back(ExampleKind::Cube);
            } else if (ex == "spherical_shell" || ex == "shell" || ex == "cube_hole") {
                cfg.examples.push_back(ExampleKind::SphericalShell);
            } else {
                std::cerr << "Unknown example: " << ex << std::endl;
                std::exit(2);
            }
        } else {
            std::cerr << "Unknown option: " << key << std::endl;
            print_usage(argv[0]);
            std::exit(2);
        }
    }

    if (cfg.levels < 1) {
        std::cerr << "--levels must be at least 1." << std::endl;
        std::exit(2);
    }
    if (cfg.nx0 < 2) {
        std::cerr << "--nx0 must be at least 2." << std::endl;
        std::exit(2);
    }
    if (cfg.nitsche_penalty <= 0. || cfg.pressure_penalty <= 0.) {
        std::cerr << "The Nitsche and pressure penalties must be positive."
                  << std::endl;
        std::exit(2);
    }
}

static std::string mesh_base_name(const Config &cfg, ExampleKind ex, int level) {
    return cfg.mesh_dir + "/" + example_name(ex) + "_" + std::to_string(level);
}

// Mesh3 opens exactly the filename passed to its constructor; it does not add
// an extension.  Older library meshes (for example cyli_0) are extensionless,
// while an earlier version of the generator wrote cube_0.mesh.  Accept both so
// that either mesh family can be used without renaming files by hand.
static std::string resolve_mesh_filename(const std::string &mesh_base) {
    const std::vector<std::string> candidates = {
        mesh_base,
        mesh_base + ".mesh"
    };

    for (const std::string &filename : candidates) {
        std::ifstream input(filename.c_str());
        if (input.good()) {
            return filename;
        }
    }

    std::cerr << "Could not open fitted mesh. Tried:\n";
    for (const std::string &filename : candidates) {
        std::cerr << "  " << filename << '\n';
    }
    std::cerr << "Run generate_fitted_maxwell_meshes.py first, or pass "
              << "the correct --mesh-dir." << std::endl;
    std::exit(1);
}

static R nominal_h(const Config &cfg, ExampleKind ex, int level) {
    const R cube_h = M_PI / (R(cfg.nx0 - 1) * R(1 << level));
    // The mesh generator uses h_shell = 0.5*h for the spherical shell.
    return (ex == ExampleKind::SphericalShell) ? 0.5 * cube_h : cube_h;
}

static int equivalent_nx(const Config &cfg, ExampleKind ex, int level) {
    const int intervals = (cfg.nx0 - 1) * (1 << level);
    // Like nominal_h(), report the doubled shell resolution used by the mesh
    // generator.  This is metadata only; the fitted shell mesh is unstructured.
    return ((ex == ExampleKind::SphericalShell) ? 2 * intervals : intervals) + 1;
}

static std::string mat_name(const Config &cfg, const std::string &AB,
                            ExampleKind ex, const std::string &method, int level) {
    return cfg.prefix + "_" + AB + "_" + example_name(ex) + "_" +
           method + "_" + std::to_string(level) + ".dat";
}

static std::string example_note(ExampleKind ex) {
    if (ex == ExampleKind::Cube) {
        return "fitted tetrahedral mesh of Omega=[0,pi]^3";
    }
    return "fitted tetrahedral spherical shell centered at (pi/2,pi/2,pi/2), radii pi/5 and pi/3";
}

static void write_manifest_row(std::ofstream &manifest,
                               ExampleKind ex,
                               const std::string &method,
                               int level,
                               int nx,
                               R h,
                               const std::string &Afile,
                               const std::string &Bfile,
                               int n0,
                               int n1,
                               int n2,
                               int nlambda,
                               const Config &cfg,
                               const std::string &bc_note) {
    manifest << example_name(ex) << ',' << method << ',' << level << ','
             << nx << ',' << nx << ',' << nx << ','
             << std::setprecision(17) << h << ','
             << Afile << ',' << Bfile << ','
             << n0 << ',' << n1 << ',' << n2 << ',' << nlambda << ','
             << ((method == "3field") ? 0. : cfg.nitsche_penalty) << ','
             << ((method == "kikuchi") ? cfg.pressure_penalty : 0.) << ','
             << 0. << ','       // tau_curl
             << 0. << ','       // tau_mass
             << 0. << ','       // tau_p
             << 0. << ','       // pressure_regularizer
             << FittedEigenData::radius_outer << ','
             << (use_harmonic_filter(cfg, ex) ? 1 : 0) << ','
             << '"' << example_note(ex) << '"' << ','
             << '"' << bc_note << '"' << '\n';
}

// Add the shell-harmonic constraint using the exact discrete space of the
// eigenfield being filtered.  This is the fitted analogue of the helper in the
// unfitted driver: the face-stabilization terms are intentionally absent.
static void add_shell_harmonic_constraint(CutFEM<Mesh3> &A,
                                          CutFEM<Mesh3> &B,
                                          CutFEM<Mesh3> &lagr,
                                          FESpace3 &harmonic_space,
                                          TestFunction<Mesh3> &trial,
                                          TestFunction<Mesh3> &test,
                                          Mesh3 &Kh,
                                          int base_dofs) {
    using namespace FittedEigenData;
    typedef FunFEM<Mesh3> Fun_h;

    // Interpolate h in the same discrete space as the filtered eigenfield:
    // Ned0 for wave/Kikuchi and RT0 for the three-field formulation.
    Fun_h harmonic(harmonic_space, fun_harmonic_two_form);

    lagr.addLinear(innerProduct(harmonic.exprList(), trial), Kh);
    Rn lag_row(lagr.rhs_);

    lagr.rhs_ = 0.;
    lagr.addLinear(innerProduct(harmonic.exprList(), test), Kh);

    A.addLagrangeVecToRowAndCol(lag_row, lagr.rhs_, 0);
    A.mat_[0][std::make_pair(base_dofs, base_dofs)] = 0.;

    // Append the same multiplier block to B, but leave its row and column zero.
    B.addLagrangeMultiplier(
        +innerProduct(harmonic.exprList(), 0 * test), 0, Kh
    );
    B.mat_[0][std::make_pair(base_dofs, base_dofs)] = 0.;
}

template <class MatrixProblem, class TrialFunction, class TestFunctionType>
static void add_tangential_nitsche(MatrixProblem &A,
                                   TrialFunction &u,
                                   TestFunctionType &v,
                                   Mesh3 &Kh,
                                   R h,
                                   R coefficient,
                                   R penalty) {
    Normal n;
    A.addBilinear(
        -innerProduct(coefficient * curl(u), cross(n, v))
        -innerProduct(coefficient * cross(n, u), curl(v))
        +innerProduct(cross(n, u), penalty / h * cross(n, v))
    , Kh, INTEGRAL_BOUNDARY);
}

static void assemble_wave(const Config &cfg,
                          ExampleKind ex,
                          int level,
                          std::ofstream &manifest) {
    using namespace FittedEigenData;
    typedef TestFunction<Mesh3> FunTest;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== " << example_name(ex)
              << ": FITTED_WAVE_EIGEN, level " << level << " ===" << std::endl;

    const std::string mesh_base = mesh_base_name(cfg, ex, level);
    const std::string mesh_file = resolve_mesh_filename(mesh_base);
    Mesh Kh(mesh_file, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Uh(Kh, DataFE<Mesh>::Ned0);
    CutFEM<Mesh> A(Uh);
    CutFEM<Mesh> B(Uh);

    FunTest u(Uh, 3, 0), v(Uh, 3, 0);
    const R mui = 1. / mu;
    const R epsi = 1. / eps;
    const R h = nominal_h(cfg, ex, level);

    A.addBilinear(+innerProduct(epsi * mui * curl(u), curl(v)), Kh);
    add_tangential_nitsche(
        A, u, v, Kh, h, epsi * mui, cfg.nitsche_penalty
    );
    B.addBilinear(+innerProduct(u, v), Kh);

    const int n_u = Uh.get_nb_dof();
    int nlambda = 0;
    if (use_harmonic_filter(cfg, ex)) {
        CutFEM<Mesh> lagr(Uh);
        add_shell_harmonic_constraint(A, B, lagr, Uh, u, v, Kh, n_u);
        nlambda = 1;
    }

    const std::string Afile = mat_name(cfg, "A", ex, "wave", level);
    const std::string Bfile = mat_name(cfg, "B", ex, "wave", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    write_manifest_row(manifest, ex, "wave", level, equivalent_nx(cfg, ex, level),
                       h, Afile, Bfile,
                       n_u, 0, 0, nlambda, cfg,
                       "symmetric fitted Hcurl Nitsche for n_cross_u_equals_0; no stabilization");
}

static void assemble_kikuchi(const Config &cfg,
                             ExampleKind ex,
                             int level,
                             std::ofstream &manifest) {
    using namespace FittedEigenData;
    typedef TestFunction<Mesh3> FunTest;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== " << example_name(ex)
              << ": FITTED_KIKUCHI_EIGEN, level " << level << " ===" << std::endl;

    const std::string mesh_base = mesh_base_name(cfg, ex, level);
    const std::string mesh_file = resolve_mesh_filename(mesh_base);
    Mesh Kh(mesh_file, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Uh(Kh, DataFE<Mesh>::Ned0);
    Space Ph(Kh, DataFE<Mesh>::P1);

    CutFEM<Mesh> A(Uh); A.add(Ph);
    CutFEM<Mesh> B(Uh); B.add(Ph);

    FunTest u(Uh, 3, 0), v(Uh, 3, 0);
    FunTest p(Ph, 1, 0), q(Ph, 1, 0);

    const R mui = 1. / mu;
    const R epsi = 1. / eps;
    const R h = nominal_h(cfg, ex, level);

    A.addBilinear(
        +innerProduct(epsi * mui * curl(u), curl(v))
        +innerProduct(grad(p), v)
        +innerProduct(u, grad(q))
        +innerProduct(0 * p, q)
    , Kh);

    add_tangential_nitsche(
        A, u, v, Kh, h, epsi * mui, cfg.nitsche_penalty
    );

    // Symmetric weak treatment of p=0.  Keep the trial expression first and
    // the test expression second in innerProduct: this is significant to the
    // expression assembler even though the scalar product is mathematically
    // commutative.
    Normal n;
    A.addBilinear(
        -innerProduct(u*n, q)
        -innerProduct(p, v*n)
        +innerProduct(cfg.pressure_penalty / h * p, q)
    , Kh, INTEGRAL_BOUNDARY);

    B.addBilinear(
        +innerProduct(u, v)
        +innerProduct(p, 0 * q)
    , Kh);

    const int n_u = Uh.get_nb_dof();
    const int n_p = Ph.get_nb_dof();
    const int base_dofs = n_u + n_p;
    int nlambda = 0;
    if (use_harmonic_filter(cfg, ex)) {
        CutFEM<Mesh> lagr(Uh); lagr.add(Ph);
        add_shell_harmonic_constraint(
            A, B, lagr, Uh, u, v, Kh, base_dofs
        );
        nlambda = 1;
    }

    const std::string Afile = mat_name(cfg, "A", ex, "kikuchi", level);
    const std::string Bfile = mat_name(cfg, "B", ex, "kikuchi", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    write_manifest_row(manifest, ex, "kikuchi", level, equivalent_nx(cfg, ex, level),
                       h, Afile, Bfile,
                       n_u, n_p, 0, nlambda, cfg,
                       "symmetric fitted Hcurl Nitsche for n_cross_u_equals_0; symmetric mixed boundary terms and penalty for p_equals_0; no stabilization");
}

static void assemble_3field(const Config &cfg,
                            ExampleKind ex,
                            int level,
                            std::ofstream &manifest) {
    using namespace FittedEigenData;
    typedef TestFunction<Mesh3> FunTest;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== " << example_name(ex)
              << ": FITTED_3FIELD_EIGEN, level " << level << " ===" << std::endl;

    const std::string mesh_base = mesh_base_name(cfg, ex, level);
    const std::string mesh_file = resolve_mesh_filename(mesh_base);
    Mesh Kh(mesh_file, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Whcurl(Kh, DataFE<Mesh>::Ned0);
    Space Uhdiv(Kh, DataFE<Mesh>::RT0);
    Space Qh(Kh, DataFE<Mesh>::P0);

    CutFEM<Mesh> A(Whcurl); A.add(Uhdiv); A.add(Qh);
    CutFEM<Mesh> B(Whcurl); B.add(Uhdiv); B.add(Qh);

    FunTest w(Whcurl, 3, 0), tau(Whcurl, 3, 0);
    FunTest u(Uhdiv, 3, 0), v(Uhdiv, 3, 0);
    FunTest p(Qh, 1, 0), q(Qh, 1, 0);

    A.addBilinear(
        -innerProduct(eps * mu * w, tau)
        +innerProduct(u, curl(tau))
    , Kh);
    A.addBilinear(
        +innerProduct(curl(w), v)
        +innerProduct(p, div(v))
    , Kh);
    A.addBilinear(+innerProduct(div(u), q), Kh);
    A.addBilinear(
        +innerProduct(0 * u, v)
        +innerProduct(0 * p, q)
    , Kh);

    B.addBilinear(
        +innerProduct(u, v)
        +innerProduct(w, 0 * tau)
        +innerProduct(p, 0 * q)
    , Kh);

    const int n_w = Whcurl.get_nb_dof();
    const int n_u = Uhdiv.get_nb_dof();
    const int n_p = Qh.get_nb_dof();
    const int base_dofs = n_w + n_u + n_p;
    int nlambda = 0;
    if (use_harmonic_filter(cfg, ex)) {
        CutFEM<Mesh> lagr(Whcurl); lagr.add(Uhdiv); lagr.add(Qh);
        add_shell_harmonic_constraint(
            A, B, lagr, Uhdiv, u, v, Kh, base_dofs
        );
        nlambda = 1;
    }

    const std::string Afile = mat_name(cfg, "A", ex, "3field", level);
    const std::string Bfile = mat_name(cfg, "B", ex, "3field", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    write_manifest_row(manifest, ex, "3field", level, equivalent_nx(cfg, ex, level),
                       nominal_h(cfg, ex, level), Afile, Bfile,
                       n_w, n_u, n_p, nlambda, cfg,
                       "natural PMC boundary condition; no stabilization");
}

int main(int argc, char **argv) {
#ifdef USE_MPI
    MPIcf cfMPI(argc, argv);
#endif

    Config cfg;
    parse_args(argc, argv, cfg);

    const std::string manifest_name = cfg.prefix + "_manifest.csv";
    std::ofstream manifest(manifest_name.c_str());
    if (!manifest) {
        std::cerr << "Could not open manifest for writing: "
                  << manifest_name << std::endl;
        return 1;
    }

    // Keep the comparison manifest schema compatible with the SLEPc reader.
    // The extra pressure_penalty column is ignored by older readers.
    manifest
        << "example,method,level,nx,ny,nz,h,Afile,Bfile,n0,n1,n2,nlambda,"
        << "penalty,pressure_penalty,tau_curl,tau_mass,tau_p,pressure_regularizer,hole_radius,"
        << "harmonic_filter,example_note,bc_note\n";

    for (ExampleKind ex : cfg.examples) {
        for (int level = 0; level < cfg.levels; ++level) {
            if (cfg.do_wave) {
                assemble_wave(cfg, ex, level, manifest);
            }
            if (cfg.do_kikuchi) {
                assemble_kikuchi(cfg, ex, level, manifest);
            }
            if (cfg.do_3field) {
                assemble_3field(cfg, ex, level, manifest);
            }
        }
    }

    std::cout << "\nWrote manifest: " << manifest_name << std::endl;
    std::cout << "Run the existing SLEPc comparison script with, for example:\n"
              << "  python3 ../cpp/mainFiles/notebooks/eigvals_compare_slepc.py "
              << "--matrix-dir . --prefix " << cfg.prefix
              << " --target 3.2 --nev 41" << std::endl;
    return 0;
}
