#include <cassert>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#ifdef USE_MPI
#include "cfmpi.hpp"
#endif

#include "finiteElement.hpp"
#include "baseProblem.hpp"
#include "paraview.hpp"
#include "../num/matlab.hpp"

// -----------------------------------------------------------------------------
// Classical fitted-FEM Maxwell cavity eigenvalue comparison.
//
// Meshes are generated by generate_fitted_maxwell_meshes.py:
//
//   cube_0.msh, cube_1.msh, cube_2.msh
//   spherical_shell_0.msh, spherical_shell_1.msh,
//   spherical_shell_2.msh
//
// Methods:
//   wave      : Ned0 curl-curl eigenproblem
//   kikuchi   : Ned0-P1 mixed eigenproblem
//   3field    : Ned0-RT0-P0 first-order eigenproblem
//
// This file contains no CutFEM geometry, Nitsche terms, ghost penalties, patch
// stabilization, or pressure regularization.  Integration is over the fitted
// tetrahedral Mesh3 directly.
//
// Strong boundary conditions:
//   wave    : n x u = 0 by eliminating boundary Ned0 edge DoFs.
//   kikuchi : n x u = 0 and p = 0 by eliminating boundary Ned0/P1 DoFs.
//   3field  : the library's fitted three-field convention strongly eliminates
//             the boundary edge DoFs of the H(curl) variable w.  The RT0 field
//             u has normal-flux DoFs and therefore cannot strongly encode the
//             tangential condition n x u = 0.  Imposing n x u = 0 on that block
//             would require changing the discrete formulation (for example a
//             boundary multiplier), not merely calling a strong-BC routine.
//
// The A/B boundary treatment follows the existing CutFEM-library eigenvalue
// examples: setDirichletHcurl or setDirichletHone on A and the corresponding
// *_RHSMat routine on B.
// -----------------------------------------------------------------------------

using namespace globalVariable;

enum class ExampleKind { Cube, SphericalShell };

static std::string example_name(ExampleKind ex) {
    return (ex == ExampleKind::Cube) ? "cube" : "spherical_shell";
}

namespace FittedEigenData {
    R eps = 1.;
    R mu  = 1.;

    R shell_center[3] = {0.5 * M_PI, 0.5 * M_PI, 0.5 * M_PI};
    R radius_inner = M_PI / 6.;
    R radius_outer = M_PI / 3.;

    R fun_0(double *P, int i) {
        (void)P;
        (void)i;
        return 0.;
    }

    // Radial harmonic representative on the shell, in centred coordinates.
    // It is smooth because r >= radius_inner > 0.
    R fun_harmonic_two_form(double *P, int i) {
        const R x = P[0] - shell_center[0];
        const R y = P[1] - shell_center[1];
        const R z = P[2] - shell_center[2];
        const R r2 = x*x + y*y + z*z;
        const R r  = std::sqrt(r2);
        const R r3 = r2 * r;
        if (i == 0) return x / r3;
        if (i == 1) return y / r3;
        return z / r3;
    }
}

struct Config {
    int nx0 = 7;
    int levels = 3;

    bool do_wave = true;
    bool do_kikuchi = true;
    bool do_3field = true;

    std::vector<ExampleKind> examples = {
        ExampleKind::Cube,
        ExampleKind::SphericalShell
    };

    std::string mesh_dir = "../cpp/mainFiles/meshes";
    std::string prefix = "eigcmp_fitted";

    bool filter_harmonic_in_shell = true;
};

static bool use_harmonic_filter(const Config &cfg, ExampleKind ex) {
    return cfg.filter_harmonic_in_shell && ex == ExampleKind::SphericalShell;
}

static void print_usage(const char *exe) {
    std::cout
        << "Usage: " << exe << " [options]\n\n"
        << "Options:\n"
        << "  --mesh-dir DIR          directory containing the generated .msh files\n"
        << "  --levels N              number of mesh levels, default 3\n"
        << "  --nx0 N                 value defining h0=pi/(nx0-1), default 7\n"
        << "  --prefix NAME           output prefix, default eigcmp_fitted\n"
        << "  --method all|wave|kikuchi|3field\n"
        << "  --example all|cube|spherical_shell\n"
        << "  --no-harmonic-filter    do not constrain the shell harmonic field\n"
        << "  --help\n";
}

static void parse_args(int argc, char **argv, Config &cfg) {
    for (int a = 1; a < argc; ++a) {
        const std::string key(argv[a]);
        auto require_value = [&](const std::string &name) -> std::string {
            if (a + 1 >= argc) {
                std::cerr << "Missing value after " << name << std::endl;
                std::exit(2);
            }
            return std::string(argv[++a]);
        };

        if (key == "--help" || key == "-h") {
            print_usage(argv[0]);
            std::exit(0);
        } else if (key == "--mesh-dir") {
            cfg.mesh_dir = require_value(key);
        } else if (key == "--levels") {
            cfg.levels = std::stoi(require_value(key));
        } else if (key == "--nx0") {
            cfg.nx0 = std::stoi(require_value(key));
        } else if (key == "--prefix") {
            cfg.prefix = require_value(key);
        } else if (key == "--no-harmonic-filter") {
            cfg.filter_harmonic_in_shell = false;
        } else if (key == "--method") {
            const std::string method = require_value(key);
            cfg.do_wave = cfg.do_kikuchi = cfg.do_3field = false;
            if (method == "all") {
                cfg.do_wave = cfg.do_kikuchi = cfg.do_3field = true;
            } else if (method == "wave") {
                cfg.do_wave = true;
            } else if (method == "kikuchi") {
                cfg.do_kikuchi = true;
            } else if (method == "3field" || method == "threefield") {
                cfg.do_3field = true;
            } else {
                std::cerr << "Unknown method: " << method << std::endl;
                std::exit(2);
            }
        } else if (key == "--example") {
            const std::string ex = require_value(key);
            cfg.examples.clear();
            if (ex == "all") {
                cfg.examples.push_back(ExampleKind::Cube);
                cfg.examples.push_back(ExampleKind::SphericalShell);
            } else if (ex == "cube") {
                cfg.examples.push_back(ExampleKind::Cube);
            } else if (ex == "spherical_shell" || ex == "shell" || ex == "cube_hole") {
                cfg.examples.push_back(ExampleKind::SphericalShell);
            } else {
                std::cerr << "Unknown example: " << ex << std::endl;
                std::exit(2);
            }
        } else {
            std::cerr << "Unknown option: " << key << std::endl;
            print_usage(argv[0]);
            std::exit(2);
        }
    }

    if (cfg.levels < 1) {
        std::cerr << "--levels must be at least 1." << std::endl;
        std::exit(2);
    }
    if (cfg.nx0 < 2) {
        std::cerr << "--nx0 must be at least 2." << std::endl;
        std::exit(2);
    }
}

static std::string mesh_base_name(const Config &cfg, ExampleKind ex, int level) {
    return cfg.mesh_dir + "/" + example_name(ex) + "_" + std::to_string(level);
}

static void assert_mesh_exists(const std::string &mesh_base) {
    const std::string filename = mesh_base + ".msh";
    std::ifstream input(filename.c_str());
    if (!input) {
        std::cerr << "Could not open fitted mesh: " << filename << "\n"
                  << "Run generate_fitted_maxwell_meshes.py first, or pass "
                  << "the correct --mesh-dir." << std::endl;
        std::exit(1);
    }
}

static R nominal_h(const Config &cfg, int level) {
    return M_PI / (R(cfg.nx0 - 1) * R(1 << level));
}

static int equivalent_nx(const Config &cfg, int level) {
    return (cfg.nx0 - 1) * (1 << level) + 1;
}

static std::string mat_name(const Config &cfg, const std::string &AB,
                            ExampleKind ex, const std::string &method, int level) {
    return cfg.prefix + "_" + AB + "_" + example_name(ex) + "_" +
           method + "_" + std::to_string(level) + ".dat";
}

static std::string example_note(ExampleKind ex) {
    if (ex == ExampleKind::Cube) {
        return "fitted tetrahedral mesh of Omega=[0,pi]^3";
    }
    return "fitted tetrahedral spherical shell centered at (pi/2,pi/2,pi/2), radii pi/6 and pi/3";
}

static void write_manifest_row(std::ofstream &manifest,
                               ExampleKind ex,
                               const std::string &method,
                               int level,
                               int nx,
                               R h,
                               const std::string &Afile,
                               const std::string &Bfile,
                               int n0,
                               int n1,
                               int n2,
                               int nlambda,
                               const Config &cfg,
                               const std::string &bc_note) {
    manifest << example_name(ex) << ',' << method << ',' << level << ','
             << nx << ',' << nx << ',' << nx << ','
             << std::setprecision(17) << h << ','
             << Afile << ',' << Bfile << ','
             << n0 << ',' << n1 << ',' << n2 << ',' << nlambda << ','
             << 0. << ','       // penalty
             << 0. << ','       // tau_curl
             << 0. << ','       // tau_mass
             << 0. << ','       // tau_p
             << 0. << ','       // pressure_regularizer
             << FittedEigenData::radius_outer << ','
             << (use_harmonic_filter(cfg, ex) ? 1 : 0) << ','
             << '"' << example_note(ex) << '"' << ','
             << '"' << bc_note << '"' << '\n';
}

static void add_shell_harmonic_constraint(CutFEM<Mesh3> &A,
                                          CutFEM<Mesh3> &B,
                                          TestFunction<Mesh3> &test,
                                          Mesh3 &Kh,
                                          int base_dofs) {
    using namespace FittedEigenData;
    typedef FunFEM<Mesh3> Fun_h;
    typedef FESpace3 Space;

    Lagrange3 vector_p2(2);
    Space harmonic_space(Kh, vector_p2);
    Fun_h harmonic(harmonic_space, fun_harmonic_two_form);

    A.addLagrangeMultiplier(+innerProduct(harmonic.exprList(), test), 0, Kh);
    A.mat_[0][std::make_pair(base_dofs, base_dofs)] = 0.;

    B.addLagrangeMultiplier(+innerProduct(harmonic.exprList(), 0 * test), 0, Kh);
    B.mat_[0][std::make_pair(base_dofs, base_dofs)] = 0.;

}

static void assemble_wave(const Config &cfg,
                          ExampleKind ex,
                          int level,
                          std::ofstream &manifest) {
    using namespace FittedEigenData;
    typedef TestFunction<Mesh3> FunTest;
    typedef FunFEM<Mesh3> Fun_h;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== " << example_name(ex)
              << ": FITTED_WAVE_EIGEN, level " << level << " ===" << std::endl;

    const std::string mesh_base = mesh_base_name(cfg, ex, level);
    assert_mesh_exists(mesh_base);
    Mesh Kh(mesh_base, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Uh(Kh, DataFE<Mesh>::Ned0);
    CutFEM<Mesh> A(Uh);
    CutFEM<Mesh> B(Uh);

    FunTest u(Uh, 3, 0), v(Uh, 3, 0);
    const R mui = 1. / mu;
    const R epsi = 1. / eps;

    A.addBilinear(+innerProduct(epsi * mui * curl(u), curl(v)), Kh);
    B.addBilinear(+innerProduct(u, v), Kh);

    const int n_u = Uh.get_nb_dof();
    int nlambda = 0;
    if (use_harmonic_filter(cfg, ex)) {
        add_shell_harmonic_constraint(A, B, v, Kh, n_u);
        nlambda = 1;
    }

    // Strong n x u = 0.  The special B routine removes the constrained rows
    // and columns from the generalized mass matrix without putting unit mass on
    // those boundary DoFs.
    Fun_h zero_u(Uh, fun_0);
    A.setDirichletHcurl(zero_u, Kh);
    B.setDirichletHcurl_RHSMat(zero_u, Kh);

    const std::string Afile = mat_name(cfg, "A", ex, "wave", level);
    const std::string Bfile = mat_name(cfg, "B", ex, "wave", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    write_manifest_row(manifest, ex, "wave", level, equivalent_nx(cfg, level),
                       nominal_h(cfg, level), Afile, Bfile,
                       n_u, 0, 0, nlambda, cfg,
                       "strong Hcurl elimination of n_cross_u_equals_0; no stabilization");
}

static void assemble_kikuchi(const Config &cfg,
                             ExampleKind ex,
                             int level,
                             std::ofstream &manifest) {
    using namespace FittedEigenData;
    typedef TestFunction<Mesh3> FunTest;
    typedef FunFEM<Mesh3> Fun_h;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== " << example_name(ex)
              << ": FITTED_KIKUCHI_EIGEN, level " << level << " ===" << std::endl;

    const std::string mesh_base = mesh_base_name(cfg, ex, level);
    assert_mesh_exists(mesh_base);
    Mesh Kh(mesh_base, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Uh(Kh, DataFE<Mesh>::Ned0);
    Space Ph(Kh, DataFE<Mesh>::P1);

    CutFEM<Mesh> A(Uh); A.add(Ph);
    CutFEM<Mesh> B(Uh); B.add(Ph);

    FunTest u(Uh, 3, 0), v(Uh, 3, 0);
    FunTest p(Ph, 1, 0), q(Ph, 1, 0);

    const R mui = 1. / mu;
    const R epsi = 1. / eps;

    A.addBilinear(
        +innerProduct(epsi * mui * curl(u), curl(v))
        +innerProduct(grad(p), v)
        +innerProduct(u, grad(q))
        +innerProduct(0 * p, q)
    , Kh);

    B.addBilinear(
        +innerProduct(u, v)
        +innerProduct(p, 0 * q)
    , Kh);

    const int n_u = Uh.get_nb_dof();
    const int n_p = Ph.get_nb_dof();
    const int base_dofs = n_u + n_p;
    int nlambda = 0;
    if (use_harmonic_filter(cfg, ex)) {
        add_shell_harmonic_constraint(A, B, v, Kh, base_dofs);
        nlambda = 1;
    }

    // Strong tangential condition on u and strong homogeneous H1 trace on p.
    Fun_h zero_u(Uh, fun_0);
    Fun_h zero_p(Ph, fun_0);
    A.setDirichletHcurl(zero_u, Kh);
    A.setDirichletHone(zero_p, Kh);
    B.setDirichletHcurl_RHSMat(zero_u, Kh);
    B.setDirichletHone_RHSMat(zero_p, Kh);

    const std::string Afile = mat_name(cfg, "A", ex, "kikuchi", level);
    const std::string Bfile = mat_name(cfg, "B", ex, "kikuchi", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    write_manifest_row(manifest, ex, "kikuchi", level, equivalent_nx(cfg, level),
                       nominal_h(cfg, level), Afile, Bfile,
                       n_u, n_p, 0, nlambda, cfg,
                       "strong Hcurl n_cross_u_equals_0 and strong H1 p_equals_0; no stabilization");
}

static void assemble_3field(const Config &cfg,
                            ExampleKind ex,
                            int level,
                            std::ofstream &manifest) {
    using namespace FittedEigenData;
    typedef TestFunction<Mesh3> FunTest;
    typedef FunFEM<Mesh3> Fun_h;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== " << example_name(ex)
              << ": FITTED_3FIELD_EIGEN, level " << level << " ===" << std::endl;

    const std::string mesh_base = mesh_base_name(cfg, ex, level);
    assert_mesh_exists(mesh_base);
    Mesh Kh(mesh_base, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Whcurl(Kh, DataFE<Mesh>::Ned0);
    Space Uhdiv(Kh, DataFE<Mesh>::RT0);
    Space Qh(Kh, DataFE<Mesh>::P0);

    CutFEM<Mesh> A(Whcurl); A.add(Uhdiv); A.add(Qh);
    CutFEM<Mesh> B(Whcurl); B.add(Uhdiv); B.add(Qh);

    FunTest w(Whcurl, 3, 0), tau(Whcurl, 3, 0);
    FunTest u(Uhdiv, 3, 0), v(Uhdiv, 3, 0);
    FunTest p(Qh, 1, 0), q(Qh, 1, 0);

    A.addBilinear(
        -innerProduct(eps * mu * w, tau)
        +innerProduct(u, curl(tau))
    , Kh);
    A.addBilinear(
        +innerProduct(curl(w), v)
        +innerProduct(p, div(v))
    , Kh);
    A.addBilinear(+innerProduct(div(u), q), Kh);
    A.addBilinear(
        +innerProduct(0 * u, v)
        +innerProduct(0 * p, q)
    , Kh);

    B.addBilinear(
        +innerProduct(u, v)
        +innerProduct(w, 0 * tau)
        +innerProduct(p, 0 * q)
    , Kh);

    const int n_w = Whcurl.get_nb_dof();
    const int n_u = Uhdiv.get_nb_dof();
    const int n_p = Qh.get_nb_dof();
    const int base_dofs = n_w + n_u + n_p;
    int nlambda = 0;
    if (use_harmonic_filter(cfg, ex)) {
        add_shell_harmonic_constraint(A, B, v, Kh, base_dofs);
        nlambda = 1;
    }

    const std::string Afile = mat_name(cfg, "A", ex, "3field", level);
    const std::string Bfile = mat_name(cfg, "B", ex, "3field", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    write_manifest_row(manifest, ex, "3field", level, equivalent_nx(cfg, level),
                       nominal_h(cfg, level), Afile, Bfile,
                       n_w, n_u, n_p, nlambda, cfg,
                       "strong Hcurl elimination on w; RT0 tangential trace is not strongly eliminable; no stabilization");
}

int main(int argc, char **argv) {
#ifdef USE_MPI
    MPIcf cfMPI(argc, argv);
#endif

    Config cfg;
    parse_args(argc, argv, cfg);

    const std::string manifest_name = cfg.prefix + "_manifest.csv";
    std::ofstream manifest(manifest_name.c_str());
    if (!manifest) {
        std::cerr << "Could not open manifest for writing: "
                  << manifest_name << std::endl;
        return 1;
    }

    // Keep the original comparison manifest columns so the same SLEPc reader
    // can be used.  Fitted-only penalty/stabilization columns are identically 0.
    manifest
        << "example,method,level,nx,ny,nz,h,Afile,Bfile,n0,n1,n2,nlambda,"
        << "penalty,tau_curl,tau_mass,tau_p,pressure_regularizer,hole_radius,"
        << "harmonic_filter,example_note,bc_note\n";

    for (ExampleKind ex : cfg.examples) {
        for (int level = 0; level < cfg.levels; ++level) {
            if (cfg.do_wave) {
                assemble_wave(cfg, ex, level, manifest);
            }
            if (cfg.do_kikuchi) {
                assemble_kikuchi(cfg, ex, level, manifest);
            }
            if (cfg.do_3field) {
                assemble_3field(cfg, ex, level, manifest);
            }
        }
    }

    std::cout << "\nWrote manifest: " << manifest_name << std::endl;
    std::cout << "Run the existing SLEPc comparison script with, for example:\n"
              << "  python3 ../cpp/mainFiles/notebooks/eigvals_compare_slepc.py "
              << "--matrix-dir . --prefix " << cfg.prefix
              << " --target 3.2 --nev 41" << std::endl;
    return 0;
}
