#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

#ifdef USE_MPI
#include "cfmpi.hpp"
#endif

#include "finiteElement.hpp"
#include "baseProblem.hpp"
#include "../num/matlab.hpp"

// -----------------------------------------------------------------------------
// Fitted-cube Maxwell eigenvalue comparison with weak boundary conditions.
//
// Geometry:
//   Omega = [0,pi]^3, loaded from the fitted meshes
//       cube_0, cube_1, cube_2, ...
//   generated by generate_fitted_maxwell_meshes.py.
//
// Methods:
//   wave      : Ned0 curl-curl eigenproblem;
//   kikuchi   : Ned0-P1 mixed eigenproblem.
//
// Unlike maxwell3D_fitted_eigen_compare.cpp, this driver retains all boundary
// degrees of freedom and imposes n x u = 0 by symmetric H(curl)-Nitsche terms.
// In the Kikuchi method, p=0 is imposed by a boundary penalty by default, as in
// the unfitted formulation.  Pass --p-bc strong to impose p=0 by elimination
// while keeping the tangential condition on u weak.  Comparing these two runs
// separates the effect of tangential Nitsche from that of the weak multiplier
// boundary condition.
//
// No cut geometry, active mesh, ghost penalty, or patch stabilization is used.
// Integration is performed directly on the fitted tetrahedral mesh.
//
// Suggested workflow from build:
//
//   ./bin/maxwell3D_fitted_cube_nitsche_eigen_compare \
//       --method all --levels 3 --nx0 7 \
//       --mesh-dir ../cpp/mainFiles/meshes \
//       --prefix eigcmp_fitted_nitsche
//
//   python3 ../cpp/mainFiles/notebooks/maxwell/eigvals_compare_slepc.py \
//       --matrix-dir . --prefix eigcmp_fitted_nitsche \
//       --target 3.2 --nev 41
//
// Optional isolation run:
//
//   ./bin/maxwell3D_fitted_cube_nitsche_eigen_compare \
//       --method kikuchi --p-bc strong --levels 3 --nx0 7 \
//       --mesh-dir ../cpp/mainFiles/meshes \
//       --prefix eigcmp_fitted_nitsche_strongp
// -----------------------------------------------------------------------------

using namespace globalVariable;

namespace FittedCubeNitscheData {
    R eps = 1.;
    R mu  = 1.;

    R fun_0(double *P, int i) {
        (void)P;
        (void)i;
        return 0.;
    }
}

enum class PressureBoundaryTreatment { Penalty, Strong };

struct Config {
    int nx0 = 7;
    int levels = 3;

    bool do_wave = true;
    bool do_kikuchi = true;

    std::string mesh_dir = "../cpp/mainFiles/meshes";
    std::string prefix = "eigcmp_fitted_nitsche";

    // Same default size as in the unfitted eigenvalue driver.
    R nitsche_penalty = 1e2;
    R pressure_penalty = 1e2;
    PressureBoundaryTreatment p_bc = PressureBoundaryTreatment::Penalty;
};

static void print_usage(const char *exe) {
    std::cout
        << "Usage: " << exe << " [options]\n\n"
        << "Options:\n"
        << "  --mesh-dir DIR          directory containing cube_0, cube_1, ...\n"
        << "  --levels N              number of mesh levels, default 3\n"
        << "  --nx0 N                 defines h0=pi/(nx0-1), default 7\n"
        << "  --prefix NAME           output prefix\n"
        << "  --method all|wave|kikuchi\n"
        << "  --nitsche-penalty X     penalty for n x u = 0, default 1e2\n"
        << "  --pressure-penalty X    boundary penalty for p = 0, default 1e2\n"
        << "  --p-bc penalty|strong   treatment of p = 0, default penalty\n"
        << "  --help\n";
}

static void parse_args(int argc, char **argv, Config &cfg) {
    for (int a = 1; a < argc; ++a) {
        const std::string key(argv[a]);
        auto require_value = [&](const std::string &name) -> std::string {
            if (a + 1 >= argc) {
                std::cerr << "Missing value after " << name << std::endl;
                std::exit(2);
            }
            return std::string(argv[++a]);
        };

        if (key == "--help" || key == "-h") {
            print_usage(argv[0]);
            std::exit(0);
        } else if (key == "--mesh-dir") {
            cfg.mesh_dir = require_value(key);
        } else if (key == "--levels") {
            cfg.levels = std::stoi(require_value(key));
        } else if (key == "--nx0") {
            cfg.nx0 = std::stoi(require_value(key));
        } else if (key == "--prefix") {
            cfg.prefix = require_value(key);
        } else if (key == "--nitsche-penalty") {
            cfg.nitsche_penalty = std::stod(require_value(key));
        } else if (key == "--pressure-penalty") {
            cfg.pressure_penalty = std::stod(require_value(key));
        } else if (key == "--p-bc") {
            const std::string value = require_value(key);
            if (value == "penalty") {
                cfg.p_bc = PressureBoundaryTreatment::Penalty;
            } else if (value == "strong") {
                cfg.p_bc = PressureBoundaryTreatment::Strong;
            } else {
                std::cerr << "Unknown --p-bc value: " << value << std::endl;
                std::exit(2);
            }
        } else if (key == "--method") {
            const std::string method = require_value(key);
            cfg.do_wave = cfg.do_kikuchi = false;
            if (method == "all") {
                cfg.do_wave = cfg.do_kikuchi = true;
            } else if (method == "wave") {
                cfg.do_wave = true;
            } else if (method == "kikuchi") {
                cfg.do_kikuchi = true;
            } else {
                std::cerr << "Unknown method: " << method << std::endl;
                std::exit(2);
            }
        } else {
            std::cerr << "Unknown option: " << key << std::endl;
            print_usage(argv[0]);
            std::exit(2);
        }
    }

    if (cfg.levels < 1) {
        std::cerr << "--levels must be at least 1." << std::endl;
        std::exit(2);
    }
    if (cfg.nx0 < 2) {
        std::cerr << "--nx0 must be at least 2." << std::endl;
        std::exit(2);
    }
    if (cfg.nitsche_penalty <= 0. || cfg.pressure_penalty <= 0.) {
        std::cerr << "Penalty parameters must be positive." << std::endl;
        std::exit(2);
    }
}

static std::string mesh_base_name(const Config &cfg, int level) {
    return cfg.mesh_dir + "/cube_" + std::to_string(level);
}

static std::string resolve_mesh_filename(const std::string &mesh_base) {
    const std::vector<std::string> candidates = {
        mesh_base,
        mesh_base + ".mesh"
    };

    for (const std::string &filename : candidates) {
        std::ifstream input(filename.c_str());
        if (input.good()) {
            return filename;
        }
    }

    std::cerr << "Could not open fitted cube mesh. Tried:\n";
    for (const std::string &filename : candidates) {
        std::cerr << "  " << filename << '\n';
    }
    std::cerr << "Run generate_fitted_maxwell_meshes.py first, or pass "
              << "the correct --mesh-dir." << std::endl;
    std::exit(1);
}

static R nominal_h(const Config &cfg, int level) {
    return M_PI / (R(cfg.nx0 - 1) * R(1 << level));
}

static int equivalent_nx(const Config &cfg, int level) {
    return (cfg.nx0 - 1) * (1 << level) + 1;
}

static std::string mat_name(const Config &cfg,
                            const std::string &AB,
                            const std::string &method,
                            int level) {
    return cfg.prefix + "_" + AB + "_cube_" + method + "_" +
           std::to_string(level) + ".dat";
}

static void write_manifest_row(std::ofstream &manifest,
                               const Config &cfg,
                               const std::string &method,
                               int level,
                               const std::string &Afile,
                               const std::string &Bfile,
                               int n_u,
                               int n_p,
                               const std::string &bc_note) {
    const int nx = equivalent_nx(cfg, level);
    manifest << "cube" << ',' << method << ',' << level << ','
             << nx << ',' << nx << ',' << nx << ','
             << std::setprecision(17) << nominal_h(cfg, level) << ','
             << Afile << ',' << Bfile << ','
             << n_u << ',' << n_p << ',' << 0 << ',' << 0 << ','
             << std::setprecision(17) << cfg.nitsche_penalty << ','
             << 0. << ','       // tau_curl
             << 0. << ','       // tau_mass
             << 0. << ','       // tau_p: no ghost penalty on a fitted mesh
             << 0. << ','       // pressure_regularizer
             << 0. << ','       // historical hole_radius column
             << 0 << ','        // harmonic_filter
             << '"' << "fitted tetrahedral mesh of Omega=[0,pi]^3" << '"' << ','
             << '"' << bc_note << '"' << '\n';
}

template <class MatrixProblem, class TrialFunction, class TestFunctionType>
static void add_tangential_nitsche(MatrixProblem &A,
                                   TrialFunction &u,
                                   TestFunctionType &v,
                                   Mesh3 &Kh,
                                   R h,
                                   R coefficient,
                                   R penalty) {
    Normal n;
    A.addBilinear(
        -innerProduct(coefficient * curl(u), cross(n, v))
        -innerProduct(coefficient * cross(n, u), curl(v))
        +innerProduct(cross(n, u), penalty / h * cross(n, v))
    , Kh, INTEGRAL_BOUNDARY);
}

static void assemble_wave(const Config &cfg,
                          int level,
                          std::ofstream &manifest) {
    using namespace FittedCubeNitscheData;
    typedef TestFunction<Mesh3> FunTest;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== cube: FITTED_WAVE_NITSCHE_EIGEN, level "
              << level << " ===" << std::endl;

    const std::string mesh_file = resolve_mesh_filename(
        mesh_base_name(cfg, level)
    );
    Mesh Kh(mesh_file, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Uh(Kh, DataFE<Mesh>::Ned0);
    CutFEM<Mesh> A(Uh);
    CutFEM<Mesh> B(Uh);

    FunTest u(Uh, 3, 0), v(Uh, 3, 0);
    const R coefficient = (1. / eps) * (1. / mu);
    const R h = nominal_h(cfg, level);

    A.addBilinear(
        +innerProduct(coefficient * curl(u), curl(v))
    , Kh);
    add_tangential_nitsche(
        A, u, v, Kh, h, coefficient, cfg.nitsche_penalty
    );

    B.addBilinear(+innerProduct(u, v), Kh);

    const std::string Afile = mat_name(cfg, "A", "wave", level);
    const std::string Bfile = mat_name(cfg, "B", "wave", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    write_manifest_row(
        manifest, cfg, "wave", level, Afile, Bfile,
        Uh.get_nb_dof(), 0,
        "symmetric fitted Hcurl Nitsche for n_cross_u_equals_0; no stabilization"
    );
}

static void assemble_kikuchi(const Config &cfg,
                             int level,
                             std::ofstream &manifest) {
    using namespace FittedCubeNitscheData;
    typedef TestFunction<Mesh3> FunTest;
    typedef FunFEM<Mesh3> Fun_h;
    typedef Mesh3 Mesh;
    typedef FESpace3 Space;

    std::cout << "\n=== cube: FITTED_KIKUCHI_NITSCHE_EIGEN, level "
              << level << " ===" << std::endl;

    const std::string mesh_file = resolve_mesh_filename(
        mesh_base_name(cfg, level)
    );
    Mesh Kh(mesh_file, MeshFormat::mesh_gmsh);
    Kh.info();

    Space Uh(Kh, DataFE<Mesh>::Ned0);
    Space Ph(Kh, DataFE<Mesh>::P1);

    CutFEM<Mesh> A(Uh); A.add(Ph);
    CutFEM<Mesh> B(Uh); B.add(Ph);

    FunTest u(Uh, 3, 0), v(Uh, 3, 0);
    FunTest p(Ph, 1, 0), q(Ph, 1, 0);

    const R coefficient = (1. / eps) * (1. / mu);
    const R h = nominal_h(cfg, level);

    A.addBilinear(
        +innerProduct(coefficient * curl(u), curl(v))
        +innerProduct(grad(p), v)
        +innerProduct(u, grad(q))
        +innerProduct(0 * p, q)
    , Kh);
    add_tangential_nitsche(
        A, u, v, Kh, h, coefficient, cfg.nitsche_penalty
    );

    Normal n;
    if (cfg.p_bc == PressureBoundaryTreatment::Penalty) {
        // Fitted analogue of e_lambda(p,q) in the unfitted Kikuchi method.
        A.addBilinear(
            -innerProduct(u*n, q)
            -innerProduct(p, v*n)
            -innerProduct(cfg.pressure_penalty / h * p, q)
        , Kh, INTEGRAL_BOUNDARY);
    }

    B.addBilinear(
        +innerProduct(u, v)
        +innerProduct(p, 0 * q)
    , Kh);

    if (cfg.p_bc == PressureBoundaryTreatment::Strong) {
        // Retain weak n x u=0, but eliminate boundary P1 degrees of freedom.
        Fun_h zero_p(Ph, fun_0);
        A.setDirichletHone(zero_p, Kh);
        B.setDirichletHone_RHSMat(zero_p, Kh);
    }

    const std::string Afile = mat_name(cfg, "A", "kikuchi", level);
    const std::string Bfile = mat_name(cfg, "B", "kikuchi", level);
    matlab::Export(A.mat_[0], Afile);
    matlab::Export(B.mat_[0], Bfile);

    const std::string p_note =
        (cfg.p_bc == PressureBoundaryTreatment::Penalty)
        ? "boundary penalty for p_equals_0"
        : "strong H1 elimination of p_equals_0";

    write_manifest_row(
        manifest, cfg, "kikuchi", level, Afile, Bfile,
        Uh.get_nb_dof(), Ph.get_nb_dof(),
        "symmetric fitted Hcurl Nitsche for n_cross_u_equals_0; " +
        p_note + "; no stabilization"
    );
}

int main(int argc, char **argv) {
#ifdef USE_MPI
    MPIcf cfMPI(argc, argv);
#endif

    Config cfg;
    parse_args(argc, argv, cfg);

    const std::string manifest_name = cfg.prefix + "_manifest.csv";
    std::ofstream manifest(manifest_name.c_str());
    if (!manifest) {
        std::cerr << "Could not open manifest: " << manifest_name << std::endl;
        return 1;
    }

    manifest
        << "example,method,level,nx,ny,nz,h,Afile,Bfile,n0,n1,n2,nlambda,"
        << "penalty,tau_curl,tau_mass,tau_p,pressure_regularizer,hole_radius,"
        << "harmonic_filter,example_note,bc_note\n";

    for (int level = 0; level < cfg.levels; ++level) {
        if (cfg.do_wave) {
            assemble_wave(cfg, level, manifest);
        }
        if (cfg.do_kikuchi) {
            assemble_kikuchi(cfg, level, manifest);
        }
    }

    std::cout << "\nWrote manifest: " << manifest_name << std::endl;
    std::cout
        << "Next step:\n  python3 "
        << "../cpp/mainFiles/notebooks/eigvals_compare_slepc.py "
        << "--matrix-dir . --prefix " << cfg.prefix
        << " --target 3.2 --nev 41" << std::endl;

    return 0;
}
